version: "3"

services:
  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    volumes:
      - ./app:/spark_app
    environment:
      - ENABLE_INIT_DAEMON=false
    hostname: spark-master
    networks:
      - mongo-net

  spark-mongo:
    image: mongo
    networks:
      - mongo-net

networks:
  mongo-net:
