version: "3"

services:
  spark-master:
    build: ./app
    environment:
      - ENABLE_INIT_DAEMON=false
    hostname: spark-master
    networks:
      - mongo-net

  spark-mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - mongo-net

networks:
  mongo-net:
